/**
 * UI Builder - Type Definitions
 */

// API Types
export interface CreateSessionResponse {
  sessionId: string;
}

export interface GenerateRequest {
  sessionId: string;
  prompt: string;
}

export interface GenerateResponse {
  status: "DONE" | "FAILED";
  artifactId: string;
  spec: UISpec | null;
  errors: string[];
  createdAt: string;
}

export interface Artifact {
  artifactId: string;
  title: string;
  status: "DONE" | "FAILED";
  spec: UISpec | null;
  errors: string[];
  createdAt: string;
}

export interface ArtifactsListResponse {
  artifacts: Artifact[];
}

// UI Spec Types (simplified for agent)
export interface UISpec {
  version: string;
  page: {
    id: string;
    title: string;
    description?: string;
  };
  layout?: {
    type: string;
    zones?: Record<string, unknown>;
  };
  toolbar?: {
    search?: boolean;
    filters?: FilterConfig[];
    actions?: ActionConfig[];
  };
  table?: {
    columns: TableColumn[];
    pagination?: boolean;
    selectable?: boolean;
  };
  drawer?: {
    enabled: boolean;
    title?: string;
  };
  [key: string]: unknown;
}

export interface FilterConfig {
  id: string;
  label: string;
  type: "select" | "date" | "text";
}

export interface ActionConfig {
  id: string;
  label: string;
  variant?: "primary" | "secondary";
  icon?: "plus" | string;
}

export interface TableColumn {
  id: string;
  label: string;
  type?: "text" | "number" | "date" | "status" | "actions";
  sortable?: boolean;
  width?: string;
  copyable?: boolean;
  actions?: {
    view?: boolean;
    edit?: boolean;
    duplicate?: boolean;
    delete?: boolean;
  };
}

// Chat Types
export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: string;
  status?: "pending" | "generating" | "validating" | "done" | "failed";
  artifactId?: string;
}

// Generation Status
export type GenerationStep = "idle" | "generating" | "validating" | "done" | "failed";

// ============================================
// Create Page (P-03 Detail Editor) Types
// ============================================

// --- Form Field (shared across patterns) ---

export type FormFieldType =
  | "input"
  | "number"
  | "textarea"
  | "select"
  | "multi-select"
  | "date-time"
  | "toggle"
  | "url"
  | "readonly";

export interface FormField {
  id: string;
  label: string;
  type: FormFieldType;
  required?: boolean;
  placeholder?: string;
  options?: string[];
  width?: "full" | "half" | "third";
  autoGenerated?: boolean;
  readOnly?: boolean;
}

// --- Editable Table Column ---

export type EditableColumnType = "input" | "number" | "select" | "custom-picker" | "readonly";

export interface EditableColumn {
  id: string;
  label: string;
  type: EditableColumnType;
  width?: string;
  options?: string[];
}

// --- Section Specs (B-01 through B-06) ---

export interface FormGroupSpec {
  type: "form";
  id: string;
  title: string;
  collapsible?: boolean;
  fields: FormField[];
  inlineActions?: { label: string; action: string }[];
}

export interface AccordionListSpec {
  type: "accordion-list";
  id: string;
  addLabel: string;
  itemTemplate: {
    titleField: string;
    hasStatusToggle?: boolean;
    actions: ("copy" | "view" | "delete")[];
    /** Optional list of inputs shown in each accordion item (like Properties Panel fields) */
    fields?: PropertyField[];
    children: SectionSpec[];
  };
}

export interface EditableTableSpec {
  type: "editable-table";
  id: string;
  title: string;
  addLabel: string;
  columns: EditableColumn[];
  hasDragHandle?: boolean;
}

export interface MasterDetailSpec {
  type: "master-detail";
  id: string;
  masterList: {
    titleField: string;
    subtitleTemplate?: string;
    actions: ("view" | "delete")[];
  };
  detailSections: SectionSpec[];
  addLabel: string;
}

export interface MediaUploadSpec {
  type: "media-upload";
  id: string;
  title: string;
  accept?: "image" | "file";
  modes: ("upload" | "url")[];
  showPreview?: boolean;
}

export interface SimpleListSpec {
  type: "simple-list";
  id: string;
  addLabel: string;
  itemTemplate: {
    fields: FormField[];
    childList?: {
      titleField: string;
      hasImage?: boolean;
      addLabel: string;
    };
  };
}

export type SectionSpec =
  | FormGroupSpec
  | AccordionListSpec
  | EditableTableSpec
  | MasterDetailSpec
  | MediaUploadSpec
  | SimpleListSpec;

// --- Properties Panel (Zone C) ---

export type PropertyFieldType =
  | "input"
  | "textarea"
  | "select"
  | "date-time"
  | "toggle-group"
  | "readonly"
  | "user-count"
  | "file-upload";

export interface PropertyField {
  id: string;
  label: string;
  type: PropertyFieldType;
  required?: boolean;
  options?: string[];
  placeholder?: string;
  autoGenerated?: boolean;
  /** Show copy-to-clipboard button next to the field (like table columns) */
  copyable?: boolean;
  readOnly?: boolean;
}

export interface PropertySection {
  id: string;
  title: string;
  fields: PropertyField[];
}

export interface PropertiesPanelSpec {
  statusToggle: boolean;
  statusLabel?: string;
  sections: PropertySection[];
  showDelete: boolean;
  extraActions?: { label: string; icon?: string; variant?: "primary" | "secondary" | "danger" }[];
}

// --- Create Page Spec (P-03) ---

export interface CreatePageSpec {
  entityName: string;
  tabs?: { id: string; label: string; sections: SectionSpec[] }[];
  sections: SectionSpec[];
  properties: PropertiesPanelSpec;
  actions: {
    saveChanges: boolean;
    saveAndClose: boolean;
    customActions?: { label: string; variant?: "primary" | "secondary" }[];
  };
  toolbar?: {
    showAddButton: boolean;
    addLabel?: string;
    showExpandCollapse: boolean;
    showPreview?: boolean;
  };
}
