/**
 * Wizard Types
 */

import type { FieldRef } from "./fieldCatalog";

// Navigation placement config
export interface CustomSection {
  id: string;
  label: string;
  icon: string;
}

export interface NavigationConfig {
  parentSection: string | null;
  newSectionName: string;
  newSectionIcon: string;
  isNewSection: boolean;
  customSections: CustomSection[];
}

// Scope options
export type ScopeType = "specific-user" | "global-queue" | "both" | null;

// Primary view options
export type PrimaryViewType = "grid" | "table" | "grid-toggle" | "create-page" | null;

// Details open behavior
export type DetailsOpenType = "side-panel" | "modal" | "separate-page" | "none" | null;

// Filter options - dynamic based on selected fields
export interface FiltersConfig {
  freeTextSearch: boolean;
  // Dynamic filters based on selected table columns (fieldId -> enabled)
  fieldFilters: Record<string, boolean>;
}

// Row action options
export interface RowActionsConfig {
  viewDetails: boolean;
  edit: boolean;
  duplicate: boolean;
  approve: boolean;
  reject: boolean;
  rejectRequiresReason: boolean;
  delete: boolean;
}

// Bulk action options
export interface BulkActionsConfig {
  approveSelected: boolean;
  rejectSelected: boolean;
  rejectRequiresReason: boolean;
}

// Confirmation options
export interface ConfirmationsConfig {
  confirmDelete: boolean;
  confirmReject: boolean;
}

// Permission roles
export type PermissionRole = "admin" | "moderator" | "support" | "viewer";

// Permissions config
export interface PermissionsConfig {
  view: PermissionRole[];
  moderate: PermissionRole[];
  delete: PermissionRole[];
}

// Selected fields config
export interface SelectedFieldsConfig {
  tableColumns: FieldRef[];
  gridFields: FieldRef[];
  detailsFields: FieldRef[];
}

// Create Page configuration (P-03 Detail Editor)
export interface CreatePageConfig {
  propertiesPanel: {
    statusToggle: boolean;
    statusLabel: string;
    showDelete: boolean;
    detailsItems?: Array<
      | { id: string; kind: "field"; label: string; type: string; required?: boolean; readOnly?: boolean; autoGenerated?: boolean; placeholder?: string; copyable?: boolean }
      | { id: string; kind: "action"; label: string }
      | { id: string; kind: "section"; title: string }
    >;
    sections: {
      id: string;
      title: string;
      fields: {
        id: string;
        label: string;
        type: "input" | "textarea" | "select" | "date-time" | "readonly";
        required?: boolean;
        readOnly?: boolean;
        autoGenerated?: boolean;
        placeholder?: string;
        copyable?: boolean;
      }[];
    }[];
  };
  sections: {
    id: string;
    type: "form" | "accordion-list" | "editable-table" | "master-detail" | "media-upload" | "simple-list";
    title: string;
    config: Record<string, unknown>;
  }[];
  saveChanges: boolean;
  saveAndClose: boolean;
  showToolbar: boolean;
}

// Full wizard intent object
export interface WizardIntent {
  featureId: string;
  title: string;
  description: string;
  navigation: NavigationConfig;
  createPageConfig: CreatePageConfig;
  selectedFields: SelectedFieldsConfig;
  filters: FiltersConfig;
  rowActions: RowActionsConfig;
  bulkActions: BulkActionsConfig;
  // Legacy fields — kept optional for backward compat with stored data
  scope?: ScopeType;
  primaryView?: PrimaryViewType;
  detailsOpen?: DetailsOpenType;
  confirmations?: ConfirmationsConfig;
  permissions?: PermissionsConfig;
}

// Wizard step definition
export interface WizardStep {
  id: number;
  title: string;
  description: string;
}

// Default wizard state
export function createDefaultWizardIntent(): WizardIntent {
  return {
    featureId: "",
    title: "",
    description: "",
    navigation: {
      parentSection: "audiences",
      newSectionName: "",
      newSectionIcon: "features",
      isNewSection: false,
      customSections: [],
    },
    createPageConfig: {
      propertiesPanel: {
        statusToggle: true,
        statusLabel: "Status",
        showDelete: true,
        sections: [
          {
            id: "details",
            title: "Details",
            fields: [
              { id: "title", label: "Title", type: "input", required: true },
              { id: "campaign-id", label: "Campaign ID", type: "input", readOnly: true, autoGenerated: true },
              { id: "comments", label: "Comments", type: "textarea", placeholder: "Provide additional information..." },
            ],
          },
        ],
      },
      sections: [
        {
          id: "zone-b-default",
          type: "accordion-list",
          title: "Accordion List",
          config: {
            titleField: "Item",
            addLabel: "+ Add Item",
            hasStatusToggle: false,
            actions: ["copy", "delete"],
            items: [
              { id: "field-1", kind: "field", label: "Title", type: "input", required: false },
            ],
            children: [],
          },
        },
      ],
      saveChanges: true,
      saveAndClose: true,
      showToolbar: true,
    },
    selectedFields: {
      tableColumns: [],
      gridFields: [],
      detailsFields: [],
    },
    filters: {
      freeTextSearch: true,
      fieldFilters: {},
    },
    rowActions: {
      viewDetails: false,
      edit: true,
      duplicate: true,
      approve: false,
      reject: false,
      rejectRequiresReason: false,
      delete: true,
    },
    bulkActions: {
      approveSelected: false,
      rejectSelected: false,
      rejectRequiresReason: false,
    },
  };
}

// Wizard steps — unified flow: always generates P-03 (create page) + P-02 (table)
export const WIZARD_STEPS: WizardStep[] = [
  { id: 0, title: "Inner Page Configurations", description: "Page which users will see when creating or editing an item" },
  { id: 1, title: "Table Configurations", description: "Choose which fields from the create page should appear as columns in the table view" },
  { id: 2, title: "Filters & Search", description: "Select which filters should be available based on your table columns" },
  { id: 3, title: "Actions", description: "What actions can users perform on table rows?" },
];

// Convert title to feature ID (kebab-case)
export function titleToFeatureId(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}
